// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImageToGrayscale(arg1) {
  return window['go']['main']['App']['ConvertImageToGrayscale'](arg1);
}

export function FetchImage() {
  return window['go']['main']['App']['FetchImage']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}
