// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ConvertImageToGrayscale(arg1) {
  return window['go']['main']['App']['ConvertImageToGrayscale'](arg1);
}

export function DecodeImage(arg1) {
  return window['go']['main']['App']['DecodeImage'](arg1);
}

export function EncodeImageToBase64(arg1) {
  return window['go']['main']['App']['EncodeImageToBase64'](arg1);
}

export function FetchImageAsBytes() {
  return window['go']['main']['App']['FetchImageAsBytes']();
}
