// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {image} from '../models';

export function ConvertImageToAscii(arg1:Array<number>):Promise<Array<any>>;

export function ConvertImageToGrayscale(arg1:Array<number>):Promise<Array<number>>;

export function DecodeImage(arg1:Array<number>):Promise<image.Image>;

export function EncodeImageToBase64(arg1:Array<number>):Promise<string>;

export function FetchImageAsBytes():Promise<Array<number>>;

export function PrintAscii(arg1:Array<any>):Promise<void>;
