// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {image} from '../models';
import {io} from '../models';

export function ConvertImageToGrayscale(arg1:image.Image):Promise<io.Writer>;

export function FetchImage():Promise<string>;

export function Greet(arg1:string):Promise<string>;
